version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client_c1
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile 
    container_name: server_c2
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules  

